/*
	Name:main.cpp
	Data:2016.3.18 15:21
	Author:czh
	Description:主函数，运行后开始模仿。
	Dependence:imitation.h
	Project：
		1.As a Client to supply robot controlling data,using tcp/ip protocol.
		2.Unit Vectors of the corresponding links in actor and imitator should be same,then use Retargeting Method solved by IK
		to identify the related joints' angles.IK algorithm takes advantages of Jacobi matrix to get the changes of joints.
		3.Control the time of executing movements by speedAdjustment() method so that we can make sure that robot NAO can finish
		the movements in a suitable and minimum time period.
		2.3249 lines(written by czh) + 1530 lines(generated by Matlab Coder).
	File System:
												definition.h
												/          \
							   robot.cpp <- robot.h	 <-	math_function.h -> math_function.cpp
												|
					   ik_solver.cpp <- ik_solver.h
												|
								   zmp.cpp <- zmp.h		  log.h -> log.cpp
												\			/
												 imitation.h -> imitation.cpp
													  |
												   main.cpp
*/
#pragma comment(lib,"ws2_32.lib")

#include "imitation.h"

int main(int argc, char **argv){
	if(argc<2){
		cout<<"The number of command line parameter should be at least two!"<<endl;
		return -2;
	}
	const int port = 8080;																// 与服务器通信端口
	int err = imitate(argv[1],port);
	if(err){
		cout<<"Error Occurs In Imitation."<<endl;
	}else{
		cout<<"Imitation Over,No Error Occurs."<<endl;
	}
	cout<<"采集处理系统关闭完成.按任意键退出程序."<<endl;
	getchar();
	return 0;
}
