// Generated by gencpp from file my_message/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MY_MESSAGE_MESSAGE_ADDTWOINTS_H
#define MY_MESSAGE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <my_message/AddTwoIntsRequest.h>
#include <my_message/AddTwoIntsResponse.h>


namespace my_message
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace my_message


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_message::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::my_message::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::my_message::AddTwoInts > {
  static const char* value()
  {
    return "my_message/AddTwoInts";
  }

  static const char* value(const ::my_message::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::my_message::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::my_message::AddTwoInts > 
template<>
struct MD5Sum< ::my_message::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_message::AddTwoInts >::value();
  }
  static const char* value(const ::my_message::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_message::AddTwoIntsRequest> should match 
// service_traits::DataType< ::my_message::AddTwoInts > 
template<>
struct DataType< ::my_message::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::my_message::AddTwoInts >::value();
  }
  static const char* value(const ::my_message::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_message::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::my_message::AddTwoInts > 
template<>
struct MD5Sum< ::my_message::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_message::AddTwoInts >::value();
  }
  static const char* value(const ::my_message::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_message::AddTwoIntsResponse> should match 
// service_traits::DataType< ::my_message::AddTwoInts > 
template<>
struct DataType< ::my_message::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::my_message::AddTwoInts >::value();
  }
  static const char* value(const ::my_message::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_MESSAGE_MESSAGE_ADDTWOINTS_H
