// Generated by gencpp from file my_message/Num.msg
// DO NOT EDIT!


#ifndef MY_MESSAGE_MESSAGE_NUM_H
#define MY_MESSAGE_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_message
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : num(0)
    , name()  {
    }
  Num_(const ContainerAllocator& _alloc)
    : num(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::my_message::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_message::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::my_message::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::my_message::Num > NumPtr;
typedef boost::shared_ptr< ::my_message::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_message::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_message::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_message

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'my_message': ['/home/freg/ros/workspace/src/my_message/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_message::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_message::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_message::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_message::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_message::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_message::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_message::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2024f0cf2e6302a28d69fe0f7dfcd317";
  }

  static const char* value(const ::my_message::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2024f0cf2e6302a2ULL;
  static const uint64_t static_value2 = 0x8d69fe0f7dfcd317ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_message::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_message/Num";
  }

  static const char* value(const ::my_message::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_message::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n\
string name\n\
";
  }

  static const char* value(const ::my_message::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_message::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_message::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_message::Num_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MESSAGE_MESSAGE_NUM_H
